name: "Sticky Pull Request Comment"
description: "Create comment on pull request, if exists update that comment."
author: "marocchino"
inputs:
  message:
    description: "comment message"
  GITHUB_TOKEN:
    description: "set secrets.GITHUB_TOKEN here"
runs:
  using: "node12"
  main: "lib/main.js"
